### PR TITLE
Add the Arabic Smith and Van Dyke version to BibleVersionCollections.ts

### PR DESCRIPTION
**Pull request by kajogo777**
Added the SVD Arabic version from bolls.life https://bolls.life/static/bolls/app/views/languages.json

Screenshot from 2022-12-25 15-30-31

Screenshot from 2022-12-25 15-30-43

### CODE REVIEW

**Comment by JPT62089** [comment]
It's great to see others contributing! I know this has been a life changer when taking sermon notes for me and to be able to have more people be able to use it in their own language is amazing! Thank you for your contribution! Hopefully Tim will be able to get this approved soon.

As one who is particular to formatting of verses, how does this work with verse numbers and what not? I'm not familiar with how verses are numbered in the Arabic language. Just as an example in English we tend to have verses either in paragraph form or verse by verse form. Pictures below for reference.

Also as a side note how are verse references formatted? This should probably be in the discussions but I'll go ahead and hijack this anyway lol

image

image

**Comment by tim-hub** [comment]
Thanks, will try to review it today

**Comment by tim-hub** [comment]
Hi @kajogo777 

Thanks for the contribution, the change is clear, and I would like to approve it,

BTW, do you mind sharing more about the number formatting in Arabic, like @JPT62089 mentioned in this comment,

https://github.com/tim-hub/obsidian-bible-reference/pull/70#issuecomment-1364732566

**Comment by kajogo777** [comment]
Thank you @JPT62089 @tim-hub 

Arabic is an RTL language, so unfortunately both the number formatting and text alignment are broken.

It's fine to have the numbers in English, but the formatting makes it a little confusing :D, maybe I'll submit another PR later to support RTL languages. 
 
Screenshot from 2023-01-14 10-58-31

**Comment by tim-hub** [comment]
> Thank you @JPT62089 @tim-hub 
> 
> Arabic is an RTL language, so unfortunately both the number formatting and text alignment are broken.
> 
> It's fine to have the numbers in English, but the formatting makes it a little confusing :D, maybe I'll submit another PR later to support RTL languages. 
>  
> Screenshot from 2023-01-14 10-58-31
> 

Thanks that will be great!

**Comment by tim-hub** [comment]
> Thanks, will try to review it today

Sorry all, I didn't manage to get it reviewed and tested it on time, will try find some time this week

**Comment by tim-hub** [comment]
Hi @kajogo777 

@JPT62089 started a discussion here, it could help for supporting RTL languages.

https://github.com/tim-hub/obsidian-bible-reference/discussions/77

**Comment by tim-hub** [comment]
this is in after resolving conflicts.

https://github.com/tim-hub/obsidian-bible-reference/pull/90

**Pull request closed without merging**
