### PR TITLE
Update Bolls Life API url to offical API

### PR DESCRIPTION
**Pull request by JPT62089**
- [Fix] Update the Bolls Life URL to resolve the issue with Bolls Life not working on mobile #55

### CODE REVIEW

**Comment by tim-hub** [comment]
Hi @JPT62089 

I used to try the original bolls life api as well, 😢   I found there is a CORS restrict for their server, this is why I changed to build a custom proxy for it, 

Does it work on your end? after change to original one?

**Comment by JPT62089** [comment]
I can re-verify later to make sure I didn't get dyslexic in my testing but I did find the original API worked on Android. I'll double check to make sure it works on both Android and Windows either tomorrow or this weekend.

**Comment by ajrty33** [comment]
Works for me on Android and Windows

**Comment by JPT62089** [comment]
@ajrty33, that's for sure with the _https://bolls.life/get-text_ API url rather than the _https://bible-api-bff.bai.uno/bolls-life_?

**Comment by ajrty33** [comment]
> @ajrty33, that's for sure with the _https://bolls.life/get-text_ API url rather than the _https://bible-api-bff.bai.uno/bolls-life_?

That's correct. The previous API didn't render the verse on Android, but the new one does. It also works on windows.

**Comment by JPT62089** [comment]
Awesome! I also just verified that my primary vault I use is actually using _https://bolls.life/get-text_. I tested functionality on both Windows and Android and it worked perfectly. I don't have any Apple devices to test though, unfortunately.

**Comment by JPT62089** [comment]
@ajrty33, have you noticed the speed at which it updates with the direct bolls life? Before I feel like I could type "--1John3:16" and it would only pop up with the 16th verse. Now it pops up with the 1st verse and then takes a second to pop up with the 16th verse. Kind of distracting at times as I'm used to just pressing enter right away.

**Comment by ajrty33** [comment]
> @ajrty33, have you noticed the speed at which it updates with the direct bolls life? Before I feel like I could type "--1John3:16" and it would only pop up with the 16th verse. Now it pops up with the 1st verse and then takes a second to pop up with the 16th verse. Kind of distracting at times as I'm used to just pressing enter right away.

I've used bolls life for ESV. I have always had to wait a second for it to populate on PC. I haven't ever been able to push enter right away. The benefit I have of using the new API is it works on mobile

**Comment by minermaniac447** [comment]
Can also confirm this fixes the issue, on both PC and mobile. I don't see any noticeable performance drop at all. Is there anything holding this back from being mainline-merged?

**Comment by tim-hub** [comment]
Thanks all for testing this, 

I was experimenting CORS issue I believe, this is why I built the proxy between the bolls api and the plugin.

Since it worked now, I am happy to see it will be merged in.

I am thinking we should add a feature in case original bolls life api raise CORS error again, then switch to the proxy. This could be a to-do.

**Comment by tim-hub** [comment]
Thanks so much again, will approve, merge and release now :)

**Pull request merged**
