### PR TITLE
clean up the outgoing links

### PR DESCRIPTION
**Pull request by tim-hub**
https://github.com/tim-hub/obsidian-bible-reference/discussions/115

image

image

I feel like it does not match a clean UI, so just try to remove them here

### CODE REVIEW

**Comment by tim-hub** [comment]
> Hello! I liked the backlinks because it helps keep track of where in my notes I'm referencing a certain piece of scripture, fully making use of Obsidian's internal linking, which is more helpful than just tags.
> 
> Would it be possible to revert this feature, but add the option of choosing where the backlink appears? e.g. either at the header, or in the body text before the tags

Technically, it is outgoing links in Obsidian, they are not backlinks. :) 

- Backlinks in Obsidian are the links other notes link to current notes.
- Outgoing links are the current note to the other notes.

---

Anyway, just to clarify, I am not again this feature, there are 2 issues here:

1. The UI, it makes the rendering logic more and more complicated, some users prefer simpler UI, others prefer more function, this is very hard to balance.

2. The Link format, Obsidian supports 2 types, dependents on user choice.
  - [[]] (by default)
  - []()
  We need a proper way to handle the link. 
  
IMHO, I personally prefer pausing this, until we can resolve these 2 issues.

**Comment by tim-hub** [comment]
> Hello! I liked the backlinks because it helps keep track of where in my notes I'm referencing a certain piece of scripture, fully making use of Obsidian's internal linking, which is more helpful than just tags.
> 
> Would it be possible to revert this feature, but add the option of choosing where the backlink appears? e.g. either at the header, or in the body text before the tags

Just another question as a user feedback (if you don't mind) @TheCatchyName 

> I may miss some perspectives

- Do you use tags or use Outgoing links  or both in this case?  
- `#john` vs `[[john]]` which do you think it is better? And why?

**Comment by TheCatchyName** [comment]
@tim-hub 

> Technically, it is outgoing links in Obsidian, they are not backlinks. :)

Thanks for the clarification, I'm still new to Obsidian and transitioning and setting up from Notion :) Your plugin has been a big help thus far!

> IMHO, I personally prefer pausing this, until we can resolve these 2 issues.

I understand the rationale behind this, I'll make do for now! If I think of any suggestions I'll do my best to make them where necessary.

> Do you use tags or use Outgoing links or both in this case?
> #john vs [[john]] which do you think it is better? And why?

From what I understand of how Obsidian works, I think I will prefer to have Bible chapters as individual pages, where I can then add themes, ideas, concepts (or even an MOC if the chapter is really dense), hence using e.g. `[[john]]`. Furthermore, outgoing and backlinks provide a way for me to navigate between pages and jump around faster, rather than just centring on a topic of `#john` and then having to perform another search of the tags to navigate around.

I'll have to do more experimentation though, because I think my understanding isn't full enough to give proper feedback :) Thank you for considering these things!

**Comment by tim-hub** [comment]
> @tim-hub 
> 
> > Technically, it is outgoing links in Obsidian, they are not backlinks. :)
> 
> Thanks for the clarification, I'm still new to Obsidian and transitioning and setting up from Notion :) Your plugin has been a big help thus far!
> 
> > IMHO, I personally prefer pausing this, until we can resolve these 2 issues.
> 
> I understand the rationale behind this, I'll make do for now! If I think of any suggestions I'll do my best to make them where necessary.
> 
> > Do you use tags or use Outgoing links or both in this case?
> > #john vs [[john]] which do you think it is better? And why?
> 
> From what I understand of how Obsidian works, I think I will prefer to have Bible chapters as individual pages, where I can then add themes, ideas, concepts (or even an MOC if the chapter is really dense), hence using e.g. `[[john]]`. Furthermore, outgoing and backlinks provide a way for me to navigate between pages and jump around faster, rather than just centring on a topic of `#john` and then having to perform another search of the tags to navigate around.
> 
> I'll have to do more experimentation though, because I think my understanding isn't full enough to give proper feedback :) Thank you for considering these things!

Thanks for sharing 👍

**Comment by cjulin6651** [comment]
This is a bummer. I did love this feature. But I understand. Would love to see it come back some day.

**Comment by tim-hub** [comment]
> This is a bummer. I did love this feature. But I understand. Would love to see it come back some day.

@cjulin6651 

Do you mind sharing how do you use the outgoing links?  and what do you think about this as well? :) thanks, if you don't mind. 


- Do you use tags or use Outgoing links or both in this case?
- #john vs [[john]] which do you think it is better? And why?

**Comment by cjulin6651** [comment]
I will start by saying, I am relatively new to Obsidian, so my processes may change some as I go, however, the sole reason I got Obsidian is to study Biblical Literary patterns. This plugin is perfect for me because it allows me to very easily quote and reference particular passages within the note. One of my goals is to visualize how each of these patterns connect to each other and see potential connections that I might have missed based on the books and chapters they connect to. As I connect passages to my notes on themes, I'll see on my graph how those themes connect to particular areas of scripture. (See example below)
image

To accompany this, my notes and file structure is built so that each book of the Bible has its own note that has prebuilt all the possible chapter tags that your app would use when I insert a note (I did this quickly with a chat GPT prompt and then just copy and pasted). That way, it auto connects to the book on the graph. As I use additional chapters in notes, I simply create a blank note for that chapter so that it visualizes on my chart. 
(See Genesis note and sidebar below as well as the primary graph).
image

I don't use the tag (at least not yet), because I played with both links and tags when formatting it, but found that, for my particular purposes, links look better when you are tracing the themes. Tags are useful for search, links are better for the visual element.

**Comment by tim-hub** [comment]
> I will start by saying, I am relatively new to Obsidian, so my processes may change some as I go, however, the sole reason I got Obsidian is to study Biblical Literary patterns. This plugin is perfect for me because it allows me to very easily quote and reference particular passages within the note. One of my goals is to visualize how each of these patterns connect to each other and see potential connections that I might have missed based on the books and chapters they connect to. As I connect passages to my notes on themes, I'll see on my graph how those themes connect to particular areas of scripture. (See example below)
> image
> 
> To accompany this, my notes and file structure is built so that each book of the Bible has its own note that has prebuilt all the possible chapter tags that your app would use when I insert a note (I did this quickly with a chat GPT prompt and then just copy and pasted). That way, it auto connects to the book on the graph. As I use additional chapters in notes, I simply create a blank note for that chapter so that it visualizes on my chart. 
> (See Genesis note and sidebar below as well as the primary graph).
> image
> 
> I don't use the tag (at least not yet), because I played with both links and tags when formatting it, but found that, for my particular purposes, links look better when you are tracing the themes. Tags are useful for search, links are better for the visual element. 

Thanks for sharing how you use it.

It is amazing.

**Comment by cjulin6651** [comment]
> Thanks for sharing how you use it.
> 
> It is amazing.

I appreciate that! I'm quite excited with the ability to study the Bible in Obsidian

**Comment by tim-hub** [comment]
@TheCatchyName @cjulin6651  this should be backed in 2.3.0 release 
image

**Pull request merged**
